theme: jekyll-theme-minimal
title: Spanish American fiction in the HathiTrust Digital Library
description: Data and contextual information for %E2%80%9CSpanish American Fiction in the HathiTrust Digital Library,%E2%80%9D a workset curated by José Eduardo González in collaboration with the HathiTrust Research Center with generous support from the Mellon Foundation.
